name: Test Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Action
        uses: ./
        with:
          pytest-coverage: './pytest-coverage.txt'
          token: ${{secrets.GITHUB_TOKEN}}